### ISSUE TITLE
Add Substring Extensions

### ISSUE THREAD

**Issue by dlumpp** [dlumpp/StringThings#2]
Useful Substring operations could be 

- `TakeFirst(int numChars)`
- `TakeLast(int numChars)`

Don't throw if they run out of chars to take

Thanks for the suggestion @VinceDio

**Comment by PODU** [comment]
I would like to work on this. 
If I have to only create the 2 methods i.e. TakeFirst and TakeLast.

**Comment by dlumpp** [comment]
Sure, open a PR if you like!

**Comment by dlumpp** [comment]
completed with #3 and published with #4 - nice work @VinceDio !
